-- Pre-deploy: Remap removed enum values before schema push
-- FINANCE_CONTROLLER/FINANCE_COORDINATOR → DIRECTOR (ApprovalLevel)
-- PENDING_FINANCE_CONTROLLER/PENDING_FINANCE_COORDINATOR → PENDING_DIRECTOR (RequestStatus)
-- FINANCE_CONTROLLER/FINANCE_COORDINATOR → FINANCE_PLANNER (Role)

UPDATE "ApprovalAction" SET "level" = 'DIRECTOR'
WHERE "level" IN ('FINANCE_CONTROLLER', 'FINANCE_COORDINATOR');

UPDATE "FinanceRequest" SET "currentApprovalLevel" = 'DIRECTOR'
WHERE "currentApprovalLevel" IN ('FINANCE_CONTROLLER', 'FINANCE_COORDINATOR');

UPDATE "FinanceRequest" SET "status" = 'PENDING_DIRECTOR'
WHERE "status" IN ('PENDING_FINANCE_CONTROLLER', 'PENDING_FINANCE_COORDINATOR');

UPDATE "User" SET "role" = 'FINANCE_PLANNER'
WHERE "role" IN ('FINANCE_CONTROLLER', 'FINANCE_COORDINATOR');

DELETE FROM "SLAConfig"
WHERE "approvalLevel"::text IN ('FINANCE_CONTROLLER', 'FINANCE_COORDINATOR');
